### PR TITLE
Major review of the documentation

### PR DESCRIPTION
**Pull request by akosma**
This pull request contains small corrections all over the documentation to improve readability and use.

### CODE REVIEW

**Comment by akosma** [comment]
@tobru @glrf For the revision process, it's recommended to checkout the `full-revision` branch and `make preview` locally.

**Review by tobru — CHANGES_REQUESTED** [review]
Some notes:

* Should the pages under "The Application Catalog" also get some love? Or are they already "good enough"?
* A few AsciiDoc errors are reported on generation, see below
* 

```
{"level":"error","time":1680504062963,"name":"asciidoctor","file":{"path":"/preview/antora/docs/modules/ROOT/pages/object-storage/create.adoc"},"source":{"url":"https://github.com/vshn/appcat-user-docs.git","local":"/preview/antora/.git","worktree":"/preview/antora","refname":"full-revision","reftype":"branch","startPath":"docs"},"msg":"target of xref not found: references/clouds.adoc#_regions"}
{"level":"error","time":1680504062964,"name":"asciidoctor","file":{"path":"/preview/antora/docs/modules/ROOT/pages/object-storage/create.adoc"},"source":{"url":"https://github.com/vshn/appcat-user-docs.git","local":"/preview/antora/.git","worktree":"/preview/antora","refname":"full-revision","reftype":"branch","startPath":"docs"},"msg":"target of xref not found: references/clouds.adoc#_regions"}
{"level":"error","time":1680504063036,"name":"asciidoctor","file":{"path":"/preview/antora/docs/modules/ROOT/pages/exoscale-dbaas/kafka/create.adoc"},"source":{"url":"https://github.com/vshn/appcat-user-docs.git","local":"/preview/antora/.git","worktree":"/preview/antora","refname":"full-revision","reftype":"branch","startPath":"docs"},"msg":"target of xref not found: references/clouds.adoc#_regions"}
{"level":"error","time":1680504063089,"name":"asciidoctor","file":{"path":"/preview/antora/docs/modules/ROOT/pages/exoscale-dbaas/mysql/create.adoc"},"source":{"url":"https://github.com/vshn/appcat-user-docs.git","local":"/preview/antora/.git","worktree":"/preview/antora","refname":"full-revision","reftype":"branch","startPath":"docs"},"msg":"target of xref not found: references/clouds.adoc#_regions"}
{"level":"error","time":1680504063145,"name":"asciidoctor","file":{"path":"/preview/antora/docs/modules/ROOT/pages/exoscale-dbaas/postgresql/create.adoc"},"source":{"url":"https://github.com/vshn/appcat-user-docs.git","local":"/preview/antora/.git","worktree":"/preview/antora","refname":"full-revision","reftype":"branch","startPath":"docs"},"msg":"target of xref not found: references/clouds.adoc#_regions"}
{"level":"error","time":1680504063203,"name":"asciidoctor","file":{"path":"/preview/antora/docs/modules/ROOT/pages/exoscale-dbaas/redis/create.adoc"},"source":{"url":"https://github.com/vshn/appcat-user-docs.git","local":"/preview/antora/.git","worktree":"/preview/antora","refname":"full-revision","reftype":"branch","startPath":"docs"},"msg":"target of xref not found: references/clouds.adoc#_regions"}
{"level":"error","time":1680504063254,"name":"asciidoctor","file":{"path":"/preview/antora/docs/modules/ROOT/pages/exoscale-dbaas/opensearch/create.adoc"},"source":{"url":"https://github.com/vshn/appcat-user-docs.git","local":"/preview/antora/.git","worktree":"/preview/antora","refname":"full-revision","reftype":"branch","startPath":"docs"},"msg":"target of xref not found: references/clouds.adoc#_regions"}
```

**Comment by akosma** [comment]
I've removed some of the build warnings, but there are two in the `crds.adoc` file that are autogenerated (same section ID, they should be different.) How is this file generated?

**Review by tobru — APPROVED** [review]
The duplicate section issue in `crds.doc` will be handled in https://github.com/vshn/appcat-user-docs/issues/48

**Review by glrf — APPROVED** [review]

**Comment by akosma** [comment]
Instamerge. Thanks everyone!

**Pull request merged**
