### PR TITLE
Add docs how to create custom database locale

### PR DESCRIPTION
**Pull request by Kidswiss**

### CODE REVIEW

**Comment by zugao** [comment]
I am not sure if we want to have the "creation of an instance" doc with "custom creation of database in that instance" doc in the same page. We need to figure out how to better organise our doc pages.

**Review by TheBigLee — APPROVED** [review]

**Comment by Kidswiss** [comment]
> I am not sure if we want to have the "creation of an instance" doc with "custom creation of database in that instance" doc in the same page. We need to figure out how to better organise our doc pages.
> 
> We could add a new page such as: `Databases & Users`

I feel like we should rework the whole docs structure. The current structure is pretty confusing and I usually need multiple tries until I find something.

But I can move it to the `Manage Users and Databases` file.

**Comment by zugao** [comment]
> > I am not sure if we want to have the "creation of an instance" doc with "custom creation of database in that instance" doc in the same page. We need to figure out how to better organise our doc pages.
> > We could add a new page such as: `Databases & Users`
> 
> I feel like we should rework the whole docs structure. The current structure is pretty confusing and I usually need multiple tries until I find something.
> 
> But I can move it to the `Manage Users and Databases` file.

I would do that so that we prevent more fragmentation

**Review by zugao — APPROVED** [review]
LGTM

**Pull request merged**
